Revert "WIP: try to move the parameter generator write build function into WAVES and out of the EABM configuration"
It doesn't appear to be possible to access a WAVES Python build function
from an SConscript parameter generator object. I think this is a
namespace issue that I don't really understand. The only change is
where the method is defined, otherwise the method is identical to the
example in the SConscript file.

Example error message:
```
write_builder_function(["build/tutorial_09_post-processing/parameter_study.h5"], ["eabm_package/python/tutorial_07_cartesian_product.py"])
scons: *** [build/tutorial_09_post-processing/parameter_study.h5] TypeError : write_builder_function() got multiple values for argument 'target'
Traceback (most recent call last):
  File "/projects/aea_compute/waves-env/lib/python3.9/site-packages/SCons/Action.py", line 1279, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
TypeError: write_builder_function() got multiple values for argument 'target'
scons: building terminated because of errors.
```

This reverts commit c130f033700ad9cd2ba22f1c9fc2b5cda11c6217.